name: Lint
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck on bash scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts/bash'
          severity: warning
          additional_files: '.github/workflows/scripts .documentation/scripts'
        env:
          SHELLCHECK_OPTS: -e SC1091
